spring:
  application:
    name: ecommerce-account
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceaccount
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate: ddl-auto=update

  security:
    user:
      name: daya
      password: test123
server:
  port : 8000